### ISSUE TITLE
Saves from previous versions are not compatible. 

### ISSUE THREAD

**Issue by Blitzerfnv** [1d51/giannan-trek#3]
Saves from V0.22 (before the mod loader) are not compatible, causing an error when attempting to load.

**Comment by 1d51** [comment]
Yeah that's possible, and there's not much to be done I'm afraid. What is the error you get?

**Comment by Blitzerfnv** [comment]
Hey. No idea what you did, but the old saves work. Yay I guess. :)

**Comment by 1d51** [comment]
I have no clue myself, but glad that it works now!
